### ISSUE TITLE
Make the CV .pdf cover the whole page (or a least bigger)

### ISSUE THREAD

**Issue by fsdias** [marvinschmitt/quarto-website-template#2]
Dear Marvin,

I was wondering if there is a way of completely embedding the .pdf the page like in this page: https://www.mjskay.com/cv.pdf
If that is not possible, is there a way of making the container cover the whole page?

In the current version version, the pdf container is too small for comfortable reading.

![image](https://github.com/marvinschmitt/quarto-website-template/assets/5689181/c31002b8-ebbd-47c5-883a-3e61bf8e96e1)

Thanks for the awesome template!

**Comment by marvinschmitt** [comment]
Hi Filipe,

thanks for reaching out, and sorry for my delayed response.

The current small PDF size has two reasons:

1. The embedded PDF reader has a toolbar with controls (top) and thumbnails (left) by default;
2. The whole PDF-embedding only spans a `column-width` in Quarto.

ad 1: I have updated the PDF container in Commit ac2f6f5759ac6711357aab9466700e470a28f5bb. This updated version now contains `#toolbar=0` to suppress the side panel. You find the exact changed line of code here: https://github.com/marvinschmitt/quarto-website-template/blob/46f36ee177bd2515f1917561cd34af4ae6048389/cv/index.qmd#L40

ad 2: I am hesitant to make the embedded PDF wider in the template. If you want to do it, you can wrap the entire `html` block of the PDF container into a wider container, such as `.column-body-outset` or `.column-page`. The result would look something like this:

~~~
:::{.column-page}
```{=html}
<p class="text-center">
  <a class="btn btn-primary btn-lg cv-download" href="`r rmarkdown::metadata$cv$pdf`" target="_blank">
    <i class="fa-solid fa-file-arrow-down"></i>&ensp;Download current CV
  </a>
</p>
<div class="embed-container">
  <iframe src="`r rmarkdown::metadata$cv$pdf`#toolbar=0" style="border: 0.5px;width: 100%;"></iframe>
</div>
```
:::
~~~

You find more of these layout options in the Quarto docs: https://quarto.org/docs/authoring/article-layout.html

I hope this helps. Let me know if it works, or if you have any other questions :-)

Cheers,
Marvin

**Comment by fsdias** [comment]
I understand. I went with: 

`   <iframe src="`r rmarkdown::metadata$cv$pdf`#toolbar=0" style="border: 0.5px;width: 100%;"></iframe> 
`
because it makes the CV big enough. If someone is interested in reading it he/she will click on "Download CV" and see it displayed full screen.

Thanks for the help and thanks again for making this template

**Comment by fsdias** [comment]
Hi, sorry to reopen this, but I had an idea. Would it be possible/feasible to to direct the user directly to the .pdf file when he/she clicks on "CV"? That is:

https://marvinschmitt.github.io/quarto-website-template/cv/cv.pdf

That way the .pdf would be displayed as in https://www.mjskay.com/cv.pdf

**Comment by marvinschmitt** [comment]
You can achieve that by adding a direct link to the PDF in your navigation bar (controlled via `_quarto.yml`). If you do that, I would recommend adding a `target="_blank"` tag to the link so that the CV opens in a new tab and visitors still have your website open in the background after they close the CV tab.

Since I prefer an embedded document to keep visitors on the actual website frame, I will leave my website template on GitHub as-is.

BTW: The current `Download` button on the `cv/` website opens the PDF in a separate tab, maybe you could consider changing your button text to something along the lines of `Open CV in Fullscreen` to have the best of both worlds?

Does that address your question or did you have something else in mind?

**Comment by fsdias** [comment]
Thanks a lot!
